# ----
# Site
title: Туроператор «Modacafe Travel»
email: mail@modacafe.travel
description: >- # this means to ignore newlines until "baseurl:"
  Туроператор «Modacafe Travel» — Эксперт на рынке туристических услуг с 2006 года
  Организация как индивидуальных так и корпоративных туров
  С нами ваш отдых перестанет быть банальным!
url: "/"
baseurl: ""
google_analytics_key:
google_maps_javascript_api_key:
disqus_shortname:

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: Moda Cafe – Оператор модного одтыха
author:
  name:
  email:
  twitter: # twitter username without the @ symbol
social:
  name: Moda cafe
  links:
    - https://github.com/modacafe/jekyll-build/

# -----
# Build

collections:
  staff_members:
    _hide_content: true

paginate: 10
paginate_path: "/blog/:num/"
permalink: pretty

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      _options:
        content:
          width: 1500
          height: 2500
  -
    scope:
      path: ""
      type: "staff_members"
    values:
      _options:
        image_path:
          width: 600
          height: 600
  -
    scope:
      path: ""
    values:
      layout: "page"
  -
    scope:
      path: "index.html"
    values:
      layout: "default"
  -
    scope:
      path: "contact.html"
    values:
      full_width: true

jekyll-archives:
  enabled:
    - categories

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE


